services:
  - type: web
    name: crop-disease-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python download_model.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
